add: 초기셋팅완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #18
Opened 2020-07-03 04:52 UTC by 7p3m1k

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-05 15:04 UTC, jamessoun93 requested changes
초기세팅 너무 잘해주셨네요 👍👍👍

아래 리뷰 남겨드렸으니 확인하시고 수정해서 새로 push 해주세요!

2020-07-05 15:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/main.html
> +        <input tyep="text" placeholder="검색" />
오타 수정해주세요 :)

2020-07-05 15:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/style/common.css
> +}
구분을 위해 블락별 한줄 씩 꼭 띄어주세요! 그리고 이런 초기화 속성들은 `common.css` 보다는 `reset.css` 라는 파일에 있는 것이 좋습니다.

2020-07-05 15:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/style/login.css
> +  align-items: center;
flexbox 사용 잘하셨습니다! 👍

2020-07-05 15:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/style/login.css
> +  align-items: flex-end;
`display: flex` 없이는 `align-items` 라는 속성이 적용되지 않습니다. flexbox 사용을 의도하셨던 거라면 flex 를 추가해주세요~

2020-07-06 09:47 UTC, joonsikyang commented
PR 템플릿도 타이틀이랑 내용 수정해주시기 바랍니다!

2020-07-07 06:16 UTC, closed without merging