add: 초기셋팅 완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #22
Opened 2020-07-03 04:53 UTC by dhgh95

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-06 06:56 UTC, joonsikyang reviewed
리뷰 내용 반영해서 수정할 수 있는 부분은 수정해주세요! :) 수고하셨습니다

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/js/login.js
> +    }
- else의 조건은 없어도 될 것 같네요! 첫 번째 if 문에 걸리는 경우, 그 외의 모든 경우 이렇게 처리해줘도 무리 없을 것 같습니다.
- 삼항연산자 적용해보세요! 코드 수정 부탁드립니다.
- 변수명, 변수 선언 키워드 전부 잘해주셨습니다🤘

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/js/main.js
> +    search.placeholder = "검색"
placeholder를 js 파일에서 작성해주신 이유가 있나요?

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/js/main.js
> +    searchImg.style.left = "5px";
이 부분은 이렇게 하기보다는 미리 클래스 안에 해당 css 속성을 정의해놓고, 새로 생긴 요소에 그 클래스명을 부여해주는 방식으로 구현하면 훨씬 좋을 것 같습니다. js파일에서는 동적인 기능, css 파일에서는 스타일 적용이 확실히 구분돼서 코드 유지보수성을 높여 주는 것이 중요합니다.

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/js/main.js
> +
불필요한 엔터는 삭제해주세요! 한 줄이면 충분할 것 같습니다 :)

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/login.html
> +
16, 28번째 줄처럼 HTML에 불필요한 엔터는 삭제해주세요! 보기 좋을 수 있겠지만 class명으로, 혹은 태그로 이미 구분이 되어 있기 때문에 한 줄 띄우는 경우는 많이 없습니다. (요소 혹은 섹션에 대한 설명이 필요하면 주석으로 표시해주세요!)

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/main.html
> +
이 부분도 불필요한 엔터는 삭제해주세요!

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/style/login.css
> + }
전체적으로 클래스명 적용 잘해주셨네요! 이해하기 좋았습니다.

2020-07-06 06:56 UTC, joonsikyang commented on students/10th/ohogeun/style/login.css
> +    font-weight: bold;
font 속성끼리는 붙여서 작성해주세요! 항상 관련도, 우선 순위 따져서 나름의 convention을 갖고 작성하는 습관을 기르는 것이 좋습니다.

2020-07-06 10:13 UTC, dhgh95 commented on students/10th/ohogeun/js/login.js
> +    }
삼항연산자로 변경했습니다

2020-07-06 10:19 UTC, dhgh95 commented on students/10th/ohogeun/js/main.js
> +    search.placeholder = "검색"
placeholder를 새로운 클래스를 add, remove하여  focus off => 중앙정렬, focus => 왼쪽정렬로  변경하였습니다.

2020-07-06 10:24 UTC, dhgh95 commented on students/10th/ohogeun/js/main.js
> +    searchImg.style.left = "5px";
넵

2020-07-06 10:24 UTC, dhgh95 commented on students/10th/ohogeun/js/main.js
> +
넵

2020-07-06 10:24 UTC, dhgh95 commented on students/10th/ohogeun/login.html
> +
넵

2020-07-06 10:24 UTC, dhgh95 commented on students/10th/ohogeun/main.html
> +
넵

2020-07-06 10:24 UTC, dhgh95 commented on students/10th/ohogeun/style/login.css
> + }
감사합니다!

2020-07-06 10:33 UTC, dhgh95 commented on students/10th/ohogeun/style/login.css
> +    font-weight: bold;
네

2020-07-07 02:54 UTC, jamessoun93 requested changes

2020-07-07 02:54 UTC, jamessoun93 commented on students/10th/ohogeun/js/login.js
> +    (idBox && pwBox) ? button.style.backgroundColor = "blue" : button.style.backgroundColor = "#B2DFFC"
`button.style.backgroundColor` 의 값만 변하는 것이기 때문에 값 부분에만 삼항연산자를 적용하시면 됩니다~
```suggestion
    button.style.backgroundColor =  (idBox && pwBox) ? "blue" : "#B2DFFC"
```

2020-07-07 02:54 UTC, jamessoun93 commented on students/10th/ohogeun/js/main.js
> +    console.log("a")
개발단계에서 사용하신 console.log() 문은 push 할 때 꼭 빼주세요!

2020-07-07 02:55 UTC, jamessoun93 commented
LGTM 이 얼마 남지 않았습니다 💪💪💪 
마지막 수정사항만 반영해서 push 해주세요!

2020-07-07 08:34 UTC, dhgh95 commented on students/10th/ohogeun/js/login.js
> +    (idBox && pwBox) ? button.style.backgroundColor = "blue" : button.style.backgroundColor = "#B2DFFC"
넵

2020-07-07 08:34 UTC, dhgh95 commented on students/10th/ohogeun/js/main.js
> +    console.log("a")
넵

2020-07-13 01:53 UTC, joonsikyang commented
LGTM👍

2020-07-13 01:54 UTC, merged