Add 초기세팅완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #29
Opened 2020-07-06 14:14 UTC by Kim-Jeong-ho7784

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
초기세팅완료
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-07 06:26 UTC, saengmotmi requested changes
코멘트 확인하시고 다시 수정해주세요!

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/login.html
> +    <div class = "login-container">
전반적으로 불필요한 줄바꿈이 많이 보이네요. 모든 부분에 표시를 하진 않겠습니다. 해당되는 부분은 수정해서 반영해주세요.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/login.html
> +      <div class = "instagram"><img src = "img/logo_text.png" ></div>
```suggestion
      <div class="instagram"><img src="img/logo_text.png"></div>
```

마찬가지로 코드 전반적으로 보이는 문제네요. 속성명과 값 사이에 간격이 없도록 해주세요. 역시 전체적으로 해당되는 부분 확인 후 수정해주세요.

또한 로고 이미지를 나타내는 부분이니까 instagram 보다는 보다 적확한 클래스명을 지어줄 수 있을 것 같습니다.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/login.html
> +              비밀번호를 잊으셨나요? </a>
```suggestion
            <a href="https://www.instagram.com/accounts/password/reset/">
              비밀번호를 잊으셨나요?
            </a>
```

html 작성하실 때 항상 요소간의 관계가 잘 보이도록 작성할 수 있도록 해주세요. 이 경우 가독성을 위해서 태그가 열리고 닫히는 걸 잘 볼 수 있도록 </a>를 아랫줄로 내려주는 게 좋겠습니다.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/main.html
> +     <link href="style/main.css" rel="stylesheet" type="text/css" />
space가 한칸 떨어져 있습니다. 사소해보이긴 하지만 indent 중요하니 잘 지켜주세요!

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/main.html
> +          <input type="text" id="navFind" placeholder="검색">
```suggestion
          <img class="navImg border" alt="camera" src="https://s3.ap-northeast-2.amazonaws.com/cdn.wecode.co.kr/bearu/logo.png">
          <img class="navImg" id="instagram" alt="instagram" src="img/logo_text.png">
          <input type="text" id="navFind" placeholder="검색">
```

속성과 속성값 간의 간격 컨벤션을 일관성 있게 지켜주세요!

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/main.html
> +                </article>
article 태그 아래에 모두 포함된 내용인 것 같은데 indentation이 지켜지지 않아서 html 태그들의 부모 자식 관계가 눈에 잘 들어오지 않네요. 2칸 간격으로 다시 줄맞춤을 해주시면 좋을 것 같습니다.

참고로 vscode를 사용하신다면 Ctrl + K, F(windows), Shift + Option + F(Mac OS)로 자동 줄맞춤을 해줄 수 있습니다.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/main.html
> +                        <span class="userId bold">wecode </span>
class의 중복되는 성질을 이용하여 bold 스타일을 잘 적용해 주셨네요 :)

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/login.css
> +      /*padding: 50px 10px 50px 10px;*/
불필요한 주석은 제거해주세요!

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/login.css
> +    border-bottom-left-radius: 10px; /* 왼쪽 아래 */
```suggestion
    border-radius: 10px;
```

input 태그의 네 귀퉁이에 모두 radius 10px을 주고 싶으셨군요. 이 경우 CSS의 단축속성을 이용하시면 간단하게 스타일링이 가능합니다. (참고 : https://developer.mozilla.org/ko/docs/Web/CSS/Shorthand_properties)

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/login.css
> +      margin-bottom: auto;
이 부분도 마찬가지로 단축 속성을 이용해 줄여주세요.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/login.css
> +      }
```suggestion
input {
  height: 30px;
}
  
.forgetpw {
  color: #00376b;
  font-size: 12px;
  line-height: 14px;
  margin: 50px auto 0;
  text-align: center;
})
```

1. 스타일과 스타일 사이는 한칸만 띄워주세요 (input, .forgetpw)
2. color가 중복되어 있네요. 이 경우 뒤에 나온 속성이 우선 적용됩니다. 알맞은 색상을 골라 하나만 적용해주세요.
3. margin에 단축 속성을 적용할 수 있겠습니다.
4. indent 일정하게 지켜주세요!

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/main.css
> +  }
웬만하면 class selector를 사용해주세요. 물론 지금 작업하고 계신 페이지의 경우 id selector가 사용되어도 무방한 경우긴 합니다. 하지만 프로젝트가 커지는 등 코드의 양이 많아지고 여러 사람이 하나의 프로젝트를 가지고 작업하게 될 경우 의도치 않은 동작을 하게 될 수 있습니다.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/main.css
> +    position: fixed;
position fixed를 주시고 top, left 등의 속성을 주지 않으셨네요. navigator 역할을 하는 요소는 화면 최상단에 붙어 있어야 하니 top: 0;을 주는게 맞아보입니다.

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/main.css
> +      background-repeat:no-repeat;
단축 속성으로 줄여주세요!

2020-07-07 06:26 UTC, saengmotmi commented on students/10th/kimjungho/style/main.css
> +    float: right;
float는 잘 사용하지 않습니다. flexbox 등을 사용해서 레이아웃을 작성해주세요!

2020-07-07 06:28 UTC, Kim-Jeong-ho7784 commented on students/10th/kimjungho/login.html
> +    <div class = "login-container">
넵 감사합니다 : )

2020-07-07 06:29 UTC, Kim-Jeong-ho7784 commented on students/10th/kimjungho/style/login.css
> +      }
넵 수정하여 반영하겠습니다 👍

2020-07-13 02:36 UTC, joonsikyang commented
정호님! 이상하게 지윤님 파일과 충돌이 났네요. 충돌만 해결해서 다시 push 해주세요.

2020-07-13 03:06 UTC, Kim-Jeong-ho7784 commented
넵 감사합니다 :)

2020년 7월 13일 (월) 오전 11:36, Joon Sik Yang <notifications@github.com>님이 작성:

> 정호님! 이상하게 지윤님 파일과 충돌이 났네요. 충돌만 해결해서 다시 push 해주세요.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wecode-bootcamp-korea/westagram-frontend/pull/29#issuecomment-657327302>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APPESOVTD5YLJ574ZBC3EDTR3JXLVANCNFSM4ORUYQLA>
> .
>

2020-07-13 05:07 UTC, saengmotmi approved these changes

2020-07-13 12:40 UTC, closed without merging