[박예진] Add: 초기 세팅 완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #30
Opened 2020-07-07 03:04 UTC by igobyyj

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 초기 세팅 완료.
		 
## 수정 사항들 자세한 내용
- 로그인 레이아웃 완료.
- 메인 페이지 미구현. 추후 작업 예정.

## 기타 질문 및 특이 사항
- 없음.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-07 06:33 UTC, saengmotmi requested changes
코멘트 확인하시고 수정 사항 반영해주세요~

2020-07-07 06:33 UTC, saengmotmi commented on students/10th/yeajinpark/login.html
> +     <link href="style/login.css" rel="stylesheet" type="text/css" />
```suggestion
    <link href="style/common.css" rel="stylesheet" type="text/css" />
    <link href="style/login.css" rel="stylesheet" type="text/css" />
```

indent 한칸 앞으로 당겨서 다른 요소들과 일치시켜주세요!

2020-07-07 06:33 UTC, saengmotmi commented on students/10th/yeajinpark/login.html
> +        <form class = "input-wrap">
```suggestion
        <img src="img/logo_text.png">
        <form class="input-wrap">
```

불필요한 줄바꿈은 없애주세요. 속성과 속성값 사이의 공백도 없애주시는게 좋겠습니다.

2020-07-07 06:33 UTC, saengmotmi commented on students/10th/yeajinpark/login.html
> +          <button> 로그인 </button>
```suggestion
          <button>로그인</button>
```

불필요한 공백이 들어 있네요. 사소해보이지만 이런 습관 하나 하나가 좋은 코드를 작성하는데 도움이 됩니다 :)

2020-07-07 06:33 UTC, saengmotmi commented on students/10th/yeajinpark/login.html
> +        <img src = "img/logo_text.png">
```suggestion
  <body>
    <div class = "background" >
      <img src = "img/logo_text.png">
```

부모 자식 태그 간의 관계는 띄어쓰기 두 칸으로 표기해주세요.

참고로 vscode를 사용하신다면 Ctrl + K, F(windows), Shift + Option + F(Mac OS)로 자동 줄맞춤을 해줄 수 있습니다.

2020-07-08 02:46 UTC, igobyyj commented on students/10th/yeajinpark/login.html
> +     <link href="style/login.css" rel="stylesheet" type="text/css" />
넵!

2020-07-08 02:50 UTC, igobyyj commented on students/10th/yeajinpark/login.html
> +        <form class = "input-wrap">
넵 공백 딜리트하겠습니다.

2020-07-08 02:56 UTC, igobyyj commented on students/10th/yeajinpark/login.html
> +          <button> 로그인 </button>
넵 공백 딜리트하겠습니다.

2020-07-08 03:00 UTC, igobyyj commented on students/10th/yeajinpark/login.html
> +        <img src = "img/logo_text.png">
꿀팁 감쟈합니다.

2020-07-13 02:22 UTC, joonsikyang reviewed
예진님! 리뷰 반영해주시고, 로그인 버튼 활성화 기능은 완성하셨으면 좋겠습니다! 잘 안 되는 부분은 질문주세요!
(참고로 github에서 질문하는 연습도 많이 해보시면 좋을 것 같습니다!)

2020-07-13 02:22 UTC, joonsikyang commented on students/10th/yeajinpark/westagram/js/login.js
> +});
다시 입력값을 지우면 버튼 색이 되돌아오나요? 확인 후 댓글로 알려주세요 :)

2020-07-13 02:22 UTC, joonsikyang commented on students/10th/yeajinpark/westagram/guide/events.md
> +- createElement로 요소 생성해서, input에 입력한 값이 추가 되어야합니다.
guide 폴더는 지워주세요!

2020-07-13 03:54 UTC, igobyyj commented on students/10th/yeajinpark/westagram/js/login.js
> +});
넵, 확인하고 다시 올리겠습니다.

2020-07-13 03:54 UTC, igobyyj commented on students/10th/yeajinpark/westagram/guide/events.md
> +- createElement로 요소 생성해서, input에 입력한 값이 추가 되어야합니다.
넵, 지우고 다시 올리겠습니다.

2020-07-30 13:09 UTC, closed without merging