[송수호] add:초기세팅완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #32
Opened 2020-07-07 04:47 UTC by kasumil

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- add:초기세팅완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
- 자바스크립트 메인에서 아직 로직을 완성하지 않았습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [v] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [v] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-07 09:37 UTC, saengmotmi requested changes

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/login.html
> +          <div class="login">
img 태그가 div 태그를 포함하는 관계가 아니죠? div 태그를 2칸 들여쓰기 해주세요.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/login.html
> +            <div class="id"><input class="bar pwInput" type="password" placeholder="비밀번호" style="width: 260px"></div>
한칸 띄어쓰기를 하면 복수의 class를 적용할 수 있다는 점을 잘 이용하셨네요. 👍
그런데 inline 스타일로 width를 주셨네요. css로 옮겨주세요!

=> 추가 미션 : 왜 inline style로 작성하는 걸 지양해야 하는지 댓글로 남겨주세요 :)

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/main.html
> +    <div class="padding_box">
기왕에 메인 내용이라고 적으신거 시맨틱 태그도 활용할 겸 main 태그로 바꿔보시는 건 어떨까요?

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/main.html
> +        <div class="profile"><img src="img/profile.png" alt="프로필" width="30px" height="30px"></div>
```suggestion
        <div class="compass">
          <img src="img/explore.png" alt="탐색" width="30px" height="30px">
        </div>
        <div class="heart">
          <img src="img/heart.png" alt="하트" width="30px" height="30px">
        </div>
        <div class="profile">
          <img src="img/profile.png" alt="프로필" width="30px" height="30px">
        </div>
```

크게 상관은 없을 거 같은데 div 태그 안에 img 태그가 포함되어 있다는 점을 좀 더 명확히 하기 위해서 위 처럼 바꿔 쓰는걸 추천드립니다!

그리고 여기도 inline 스타일... css로 옮겨주세요!

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/js/login.js
> +console.log(info, pwd)
사용하지 않는 console.log는 지워주세요.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/js/login.js
> +});
1. 함수 내에서 e(이벤트 객체)가 사용되지 않으니 지워주세요.

지우시기 전에 함수 안에 console.log(e) / console.log(e.target) / console.log(e.target.value) 바꿔가면서 각각의 값이 어떻게 나타나는지 확인해보면 좋겠네요.

2. indent 지켜주세요!

```suggestion
document.addEventListener('keyup', function(e) {
  if (info.value !== "" && pwd.value !== "") { 
    let color = document.getElementById('loginbtn');
    color.style.backgroundColor = 'blue';
   }
})
```

3. color 변수에 담아주신 #loginbtn 요소는 함수가 호출되어 조건문을 통과할 때마다 정의되고 있네요. 동작에는 문제가 없지만 코드 가독성과 효율을 위해 info, pwd와 함께 두어도 좋겠습니다.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/js/main.js
> +document.addEventListener(keyup, function(e) {
불필요한 줄바꿈 삭제해주세요!

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/js/main.js
> +let push = document.c
push 하시기 전에 아직 완성 안된 부분 잘 확인하시고 올려주세요!

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/main.html
> +              <div class="ol-div">
리스트 요소는 `<ul>` `<ol>` 태그 아래에 `<li>` 태그를 자식 요소로 넣어 작성하시면 됩니다.
지금 ul(unordered list) 태그 아래 다시 ol(ordered list) 태그로 열어주시고 자식 요소는 li가 아닌 div로 주셨네요!
아래 자료 참고하시고 고쳐주세요!

참고 : https://www.w3schools.com/html/html_lists.asp

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/main.html
> +          <article class="article">
시맨틱 태그 굿!

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/main.html
> +            <li>
여기는 ul 태그 아래 li 태그 잘 쓰셨네요!

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/login.css
> +    padding: 9 0 7 8;
px 등 단위를 적어주셔야 padding 값이 적용됩니다. 브라우저 개발자도구에서 해당 요소의 css 속성 invalid value라고 뜨는 거 확인해주세요.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/login.css
> +    border-width: 1px;
border 단축 속성에 써주신 3개의 값은 각각 다음과 같습니다.
- border-width : 1px
- border-style: solid;
- border-color: gray;

그런데 다음 줄을 보시면 이미 적용된 border-width를 다시 한번 적용해주고 계시네요. 수정해주세요!

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/main.css
> +    display: flex;
잘 작성해 주셨는데 더 중요한 요소를 위로 올려주세요. 이 경우에는 justifiy-content와 display: flex의 자리를 서로 바꿔줘야겠네요.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/main.css
> +} */
주석처리하신 불필요한 코드는 push 전 삭제해주세요.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/main.css
> +    display: flex;
```suggestion
    display: flex;
    justify-content: center;
    margin: 0 87.5px;
    padding-top: 30px;
```
이 내용도 마찬가지 내용입니다. 기왕이면 중요한 내용을 위로, 연관성 있는 속성들 끼리 묶어서 정리해주세요. 나중에 스타일을 이리저리 고치다가 속성을 중복 적용하는 등의 경우를 방지할 수 있습니다.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/main.css
> +    box-sizing: border-box;
이 부분은 처음부터 전체에 적용될 수 있도록
```
* {
  box-sizing: border-box;
}
```
이렇게 작성해주셨어야 하는 내용 아닐까요? common.css 쪽으로 가는 쪽이 맞아보입니다.

여기에만 특별히 작성하신 이유가 궁금하네요.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/main.css
> +}
꼭 이 부분에 대한 코멘트는 아니지만 전체적으로 모든 요소들의 높이와 가로 너비가 고정값으로 주어져 있네요.
block 요소의 경우 부모 요소의 높이나 너비가 정해져 있으면 자동으로 가로 100%를 차지하게 됩니다.
이러한 성질을 잘 이용한다면 모든 요소에 고정 값을 주지 않아도 됩니다.
특히 나중에 반응형 디자인을 적용하게 될 경우 특히 중요해집니다.

2020-07-07 09:37 UTC, saengmotmi commented on students/10th/songsuho/style/main.css
> +    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
혹시 이 폰트들이 friends class selector를 가진 요소들에만 적용되는 건가요? 그게 아니라면 common.css로 가는 쪽이 맞아보이네요.

2020-07-07 09:37 UTC, saengmotmi requested changes
코멘트 확인하시고 수정 사항 반영해주세요!

2020-07-08 12:34 UTC, kasumil commented on students/10th/songsuho/login.html
> +          <div class="login">
수정완료했습니다.

2020-07-08 12:34 UTC, kasumil commented on students/10th/songsuho/login.html
> +            <div class="id"><input class="bar pwInput" type="password" placeholder="비밀번호" style="width: 260px"></div>
수정하였습니다.
그 당시 길이가 수정되지 않았으나 이유가 아마도 style : "width = 260px"; 그대로 css에 넣어 작동하지 않은 것이 원인으로 생각합니다.
또한, inline 스타일을 작성을 지양해야하는 이유로는 관리의 용이성때문에 css를 작성해야합니다. 
html에 작성하면 해당 문제를 찾기위해서 작성한 코딩을 일일히 흝어보면서 찾아야하지만, 
이와 반대로 css에서는 조작함에 따라 수정할 수 있기때문입니다.

2020-07-08 12:34 UTC, kasumil commented on students/10th/songsuho/main.html
> +    <div class="padding_box">
수정하려했지만 main으로 할 경우 flex가 무효화 되어 그냥 두어야 할 것 같습니다.

2020-07-08 12:34 UTC, kasumil commented on students/10th/songsuho/main.html
> +        <div class="profile"><img src="img/profile.png" alt="프로필" width="30px" height="30px"></div>
수정하였습니다.

2020-07-08 12:34 UTC, kasumil commented on students/10th/songsuho/js/login.js
> +console.log(info, pwd)
삭제하였습니다

2020-07-08 12:34 UTC, kasumil commented on students/10th/songsuho/style/main.css
> +} */
삭제하였습니다.

2020-07-08 12:36 UTC, kasumil commented on students/10th/songsuho/style/main.css
> +    display: flex;
수정하였습니다.

2020-07-08 12:37 UTC, kasumil commented on students/10th/songsuho/style/main.css
> +    box-sizing: border-box;
몰라서.... 작성하였습니다.  수정하였습니다.

2020-07-08 12:40 UTC, kasumil commented on students/10th/songsuho/style/main.css
> +    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
해당 폰트 family는 common.css로 이동하였습니다.

2020-07-08 12:41 UTC, kasumil commented on students/10th/songsuho/style/main.css
> +}
좌우를 auto로 넣으면 깨져서 부득이하게 그부분을 통제하지 못하여 작성하였는데,  그부분을 좀 더 공부해서 잡아야할 것 같습니다.

2020-07-13 02:29 UTC, merged