[박민규] add: 초기셋팅 완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #36
Opened 2020-07-07 06:15 UTC by 7p3m1k

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
  - 깃허브에 재등록 했습니다.
## 수정 사항들 자세한 내용
- .history가 같이 psuh 되어서 다시 브랜치를 만들어서 올립니다.

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-08 06:04 UTC, jamessoun93 requested changes

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/index.html
> +    <p></P>
불필요한 p 태그는 없애주세요~

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/login.js
> +const loginEvent = document.getElementsByClassName("loginbutton")[0];
`document.getElementsByClassName` 을 통해 해당하는 html 요소를 가지고 오는것이기 때문에 변수이름을 `loginEvent` 보다 `loginBtn` 처럼 한눈에 파악하기 쉬운 이름으로 변경해주세요~!

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/login.js
> +const iDpWinfo = document.getElementsByClassName("login")[0];
구분을 위해 이런 변수 선언문들은 전부 위쪽으로 모아주세요!

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/login.js
> +  if (idValue !== "" && pwValue !== "") {
구분을 위해 위에 변수 선언문과 if 문 사이에 빈줄을 추가해주세요

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/login.js
> +  }
이런 부분은 삼항연산자를 적용해볼 수 있습니다! 한번 적용해보세요!!

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/main.js
> +  if (replyValue !== "") {
여기도 마찬가지로 위에 빈 줄을 추가해주세요~

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/main.js
> +    return;
여기에 `return;` 이 들어간 이유가 있나요?!

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/main.js
> +) /*함수안에 envent 쓴이유*/ {
가독성을 위해 아래처럼 수정해주세요!
```suggestion
inputEnter.addEventListener("keyup", function (event) {
```

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/main.js
> +  console.log(event.keyCode);
개발단계에서 사용하신 콘솔로그문은 지워주세요!

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/login.js
> +const iDpWinfo = document.getElementsByClassName("login")[0];
전부 위로 올려주시게 되면 바로 위 클릭 이벤트리스너에서도 새로 찾아서 value 를 접근할 필요가 없어집니다!

2020-07-08 06:04 UTC, jamessoun93 commented on students/10th/ParkMinKyu/js/main.js
> +    return;
마찬가지로 불필요한 `return;` 문 입니다~

2020-07-08 06:23 UTC, 7p3m1k commented on students/10th/ParkMinKyu/index.html
> +    <p></P>
감사합니다 수정했습니다.

2020-07-08 06:25 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/login.js
> +const loginEvent = document.getElementsByClassName("loginbutton")[0];
네 참고하겠습니다.

2020-07-08 06:28 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/login.js
> +const iDpWinfo = document.getElementsByClassName("login")[0];
수정했습니다. !

2020-07-08 06:29 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/login.js
> +  if (idValue !== "" && pwValue !== "") {
구분하는 연습 하겠습니다.

2020-07-08 06:35 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/main.js
> +    return;
없습니다..

2020-07-09 04:37 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/login.js
> +  }
적용 완료했씁니다!

2020-07-09 04:37 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/main.js
> +  if (replyValue !== "") {
수정 완료했습니다.

2020-07-09 04:37 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/main.js
> +) /*함수안에 envent 쓴이유*/ {
수정 완료했습니다.

2020-07-09 04:37 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/main.js
> +  console.log(event.keyCode);
제거 했습니다.

2020-07-09 04:37 UTC, 7p3m1k commented on students/10th/ParkMinKyu/js/main.js
> +    return;
리턴 제거 했습니다 .

2020-07-13 02:31 UTC, merged