ADD: 필수구현사항 구현완료
wecode-bootcamp-korea/westagram-frontend-deprecated pull request #58
Opened 2020-07-31 04:35 UTC by sangkuOH

- 페이지 레이아웃 구현 완료
- 자바스크립트 필수 기능 구현 완료

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-31 06:29 UTC, dipsiiiiiiiiii commented
다른 동기분 PR 날리신 거 참고해서 PR 제목에 이름 넣어주세요 :)

2020-07-31 06:39 UTC, sangkuOH commented
PR 제목, 마크다운 수정완료 하였습니다.

2020-07-31 10:38 UTC, dipsiiiiiiiiii reviewed
우선 login 페이지부터 리뷰 반영해주시고 다시 push 해주세요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +      <article>
article 태그를 쓰신 이유가 있나요?

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +        <div class="log-img-container">
이름을 지을 떄는 camelCase와 snake_case 둘 중에 사용하는데 javascript에서는 camelCase를 사용하셔야 합니다. 지금 다 바꾸실 필요는 없고 다음 프로젝트 부터는 camelCase로 해주시면 됩니다 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/js/login.js
> +});
코드 너무 잘 짜셨는데 btnOn과 btnOff 함수를 합칠 수도 있을 것 같애요!

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +        <div class="log-img-container">
그리고 login을 줄여서 log로 하신 것 같은데 log라고만 하면 login으로 유추하기는 어려울 것 같습니다! login은 짧으니까 굳이 안 줄이셔도 될 것 같애요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +        </div>
그리고 로그인 박스 왼쪽 이미지를 구현 하시려다가 안하신 것 같은데 지워주시면 좋을 것 같습니다!

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +                <div class="log-content-1-input" id="con-mg">
숫자가 들어가는 건 좋지 않은 것 같습니다. 한 번에 의미를 파악할 수 있게 다시 고민해주세요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +                </div>
태그마다 레이아웃을 위해서 굳이 div 태그를 감싸주실 필요는 없을 것 같습니다. input태그에 margin을 줄 수도 있고 input 2개와 로그인 버튼을 하나의 div로 묶어서 padding을 줄 수도 있을 것 같습니다. div는 레이아웃을 위해 최소한으로만 사용하려고 노력해주세요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +                </div>
라인을 만들기 위해서 div를 쓰셨는데 inline 속성으로 쓰시는 거니까 span을 쓸 수도 있을 것 같네요! 앞서 말씀드린 대로 숫자는 class 이름에서는 좋은 것 같지 않습니다.

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +            <P>계정이 없으신가요?</P>
대문자 P를 소문자로 바꿔주세요! 그리고 p 태그 쓰신 이유는 뭔가요!? 🤔

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +            </ul>
li 태그 쓰신 거 너무 잘하셨네요! :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +
빈 칸 지워주세요 ;)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +
빈 칸 지워주세요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +    background-size: 52%;
background를 쓰시려면 size도 합칠 수 있을 것 같습니다! size는 px로 주시면 될 거 같애요!

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +
빈 칸 지워주세요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/main.html
> +
빈 칸 지워주세요 :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +    background-size: 454px 618px;
이거도 하나로 합쳐줄 수 있을 거 같애요! :)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +
그리고 var를 쓰신 이유가 있나요!?

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +
빈 칸 지워주세요!

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +    align-items: center;
이렇게 붙여서 쓰신 거 너무 좋네요 ;)

2020-07-31 10:38 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/style/login.css
> +    background-size: 440px 411px;
background 쓰시려면 다 합치실 수 있어요!

2020-07-31 10:40 UTC, dipsiiiiiiiiii commented on students/11th/snagkuoh/login.html
> +            </ul>
그런데 배열의 map 메서드 사용하면 짧게 줄일 수 있을 것 같네요 ;)

2020-08-01 10:09 UTC, sangkuOH commented on students/11th/snagkuoh/login.html
> +      <article>
main 태그의 자식요소로 가운데정렬을 위한 요소로 사용하였습니다.
div 태그를 사용해도되지만 가독성을 위해 사용해보았습니다.

2020-08-01 10:09 UTC, sangkuOH commented on students/11th/snagkuoh/login.html
> +        <div class="log-img-container">
넵 시간이 되면 클래스명 수정해보겠습니다!

2020-08-01 10:10 UTC, sangkuOH commented on students/11th/snagkuoh/js/login.js
> +});
넵! else if 통해서 병합해보겠습니다!

2020-08-01 10:16 UTC, sangkuOH commented on students/11th/snagkuoh/login.html
> +        </div>
로그인 좌측의 아이폰 이미지가 아이폰 이미지와 내부 피드이미지가 각각 나눠져 있어서 인스타 내부 이미지를 위해 class를 생성하였습니다. :)

2020-08-01 10:20 UTC, sangkuOH commented on students/11th/snagkuoh/main.html
> +
넵

2020-08-03 05:30 UTC, jamessoun93 commented
상구님! 커밋메세지 가이드라인 지켜주세요!

2020-08-03 06:13 UTC, jamessoun93 requested changes

2020-08-03 06:13 UTC, jamessoun93 commented on students/11th/snagkuoh/js/login.js
>      btnOn();
이 부분은 addEventListener 의 두번째 인자로 function 을 선언해주고 그 안에서 btnOn() 함수를 호출하기보다는, btnOn 함수의 reference 를 바로 넣어주는게 훨씬 깔끔해지겠네요!

아래 처럼요!
`inputId.addEventListener('keydown', btnOn);`

2020-08-03 06:13 UTC, jamessoun93 commented on students/11th/snagkuoh/js/main.js
> +})();
코드상으로 봤을때는 clickLikeButton 함수가 실행되자마자 like 라는 변수에 false 라는 boolean value 를 지정하고, 아래서 return 하는 함수에서 like 를 true 로 바꿔주는 방식인것 같은데요. 항상 false -> true 로 바뀌는 구조인데, 아래 조건문이 필요할까 싶습니다. 

왜 이렇게 구현하셨는지 설명 부탁드려도 될까요?!

2020-08-04 18:32 UTC, saengmotmi reviewed
코멘트 확인해주세요

2020-08-04 18:32 UTC, saengmotmi commented on students/11th/snagkuoh/js/login.js
> +let signIn = document.querySelector('.loginFormWrap');
const가 아닌 let으로 선언하신 이유가 특별히 있으신가요? 재할당될 값이 아니기 때문에 const로 쓰는게 좋아보입니다

2020-08-04 18:32 UTC, saengmotmi commented on students/11th/snagkuoh/js/login.js
>      btn.disabled = false;
```suggestion
    if (inputId.value && inputPw.value) {
      btn.disabled = false; 
```
두 칸 들여쓰기 해주세요

2020-08-04 18:32 UTC, saengmotmi commented on students/11th/snagkuoh/js/main.js
> +        <button class = "userId">539_ku</button>
완전 굿굿 👍

2020-08-04 18:32 UTC, saengmotmi commented on students/11th/snagkuoh/style/main.css
> +    background: none;
원래 background 요소가 존재했던 dom의 내용을 바꿔주는게 아닌거 같아서 꼭 필요한 부분인가 여쭙습니다

2020-08-04 18:32 UTC, saengmotmi commented on students/11th/snagkuoh/main.html
>        <div class="feeds">
포함 관계라면 두칸 들여쓰기로 구분해주세요

2020-08-04 18:32 UTC, saengmotmi commented on students/11th/snagkuoh/js/main.js
>          replyBtn.classList.remove = 'reply-btn-off';
```suggestion
        const { value } = replyArea
        replyBtn.disabled = !value;
        replyBtn.classList = value ? 'reply-btn-active' : 'reply-btn-off';
        replyBtn.classList.remove = value ? 'reply-btn-off' : 'reply-btn-active';
```
if 문 제거하고 이런 방식은 어떨까요?

2020-08-26 04:58 UTC, closed without merging